ALTER TABLE vultrac_issue_staging
ADD REMEDIATION_PRIORITY VARCHAR(15),
ADD PROTOCOL VARCHAR(100),
ADD TRANSPORT VARCHAR(100);

-- 13-06-2025
/*
ALTER TABLE vultrac_issue_staging
ADD ISSUE_COMMENTS VARCHAR(2500);
*/

-- 19-06-2025 currently using ISSUE_UPLOAD_COMMENTS
ALTER TABLE vultrac_issue_staging
DROP COLUMN ISSUE_COMMENTS;
 
 
 -- 19-06-2025
ALTER TABLE vultrac_issue_staging
ADD UPLOAD_TYPE_ID INT DEFAULT 1;