CREATE TABLE `vultrac-edge`.vultrac_issue_upload_type (
    UPLOAD_TYPE_ID INT PRIMARY KEY,
    UPLOAD_TYPE_NAME VARCHAR(100),
    UPLOAD_TYPE_DESC VARCHAR(500),
    ACTIVE_FLAG VARCHAR(10),
    MODIFIED_BY VARCHAR(45),
    CREATED_BY VARCHAR(45),
    CREATED_DT TIMESTAMP(6)
);
 